version: '2'
services:
  rest:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - web
   
  web:
    image: andrewc2020/studentsfrontend
    ports:
      - "3000:3000"