version: '3'

services:
  example-service:
    build: .
   
      
    
    env_file:
           - .env
    volumes:
           - .:/usr/src/app
           - /usr/src/app/node_modules
    ports:
         - 3000:8000
         - 9229:9229
    
    
    
    
    
    command: npm run execute