apiVersion: v1
kind: Service
metadata:
  name: students-backend
  labels:
    app: students
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: students
    tier: backend
  ports:
  - port: 8000
    targetPort: http-server

---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: students
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: students
        tier: backend
    template:
      metadata:
        labels:
          app: students
          tier: backend
      spec:
        containers:
          - name: students
            image: gcr.io/mycal-255414/students
            ports:
              - containerPort: 8000
                name: http-server
            env:
              - name: DATABASE_URL
                value: mongodb://mongo:27017/test
              - name: PORT
                value: "8000"
  
            imagePullPolicy: IfNotPresent
  